replicas: 2

gcp:
  databaseInstance: ent-baba-tst:europe-west1:baba-db-pg13

chouette:
  service: http://chouette.tst.entur.internal

ingress:
  domain: .staging.entur.io
  organizations:
    name: timetable-admin-v1-organisations-gcp2
  providers:
    name: timetable-admin-v1-providers-gcp2

auth0:
  ror:
    url: https://ror-entur-staging.eu.auth0.com/
    audience: https://ror.api.staging.entur.io
  entur:
    internal:
      url: https://internal.staging.entur.org/
    partner:
      url: https://partner.staging.entur.org
  admin:
    client:
      id: JyhRpz2uzDSEKuNdUQMD10wm7y5qiePT
    domain: ror-entur-staging.eu.auth0.com

mail:
  newUserFrom: noreply-staging@entur.org
  link:
    routeDB: https://rutedb.staging.entur.org/
    stopPlace: https://stoppested.staging.entur.org/
    operator: https://operator-stage.rutebanken.org/

monitoringEnabled: true
