apiVersion: v1
data:
  application.properties: |+
    spring.profiles.active=auth0
    spring.jpa.database=POSTGRESQL
    spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
    spring.jpa.open-in-view=false
    spring.datasource.platform=postgres
    spring.cloud.gcp.sql.database-name=baba
    spring.cloud.gcp.sql.instance-connection-name={{ .Values.gcp.databaseInstance }}
    spring.database.driverClassName=org.postgresql.Driver
    spring.flyway.table=schema_version
    spring.mail.properties.mail.smtp.starttls.enable=true
    spring.mail.port=2525
    spring.mail.properties.mail.smtp.writetimeout=5000
    spring.mail.properties.mail.smtp.ssl.enable=false
    spring.mail.host=smtp.postmarkapp.com
    spring.mail.properties.mail.smtp.timeout=3000
    spring.mail.properties.mail.smtp.connecttimeout=5000

    new.user.email.enabled=true
    new.user.email.from={{ .Values.mail.newUserFrom}}

    iam.auth0.admin.domain={{ .Values.auth0.admin.domain }}
    iam.auth0.admin.client.id={{ .Values.auth0.admin.client.id }}


    #OAuth2 Resource Server
    spring.security.oauth2.resourceserver.jwt.issuer-uri={{ .Values.auth0.ror.url }}
    baba.oauth2.resourceserver.auth0.ror.jwt.audience={{ .Values.auth0.ror.audience }}
    baba.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    server.port={{ .Values.service.http.internalPort }}
    server.compression.enabled=true
    chouette.rest.referential.base.url={{ .Values.chouette.service }}/chouette_iev/referentials
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState,db
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    rutebanken.kubernetes.namespace={{ .Release.Namespace }}

kind: ConfigMap
metadata:
  name: {{ template "baba.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
