keycloakUrl: https://kc-dev.devstage.entur.io/auth
mail:
  newUserFrom: noreply@entur.org
  link:
    routeDB: https://rutedb.dev.entur.org/
    stopPlace: https://stoppested.dev.entur.org/
    operator: https://operator-test.rutebanken.org/