env: production
replicas: 2

gcp:
  databaseInstance: entor-ror-prod:europe-west1:baba-db-1=tcp:5432
  exchangeKeyName: marduk-exchange-neon-storage-key

keycloakUrl: https://auth.entur.org/auth

mail:
  newUserFrom: noreply@entur.org
  link:
    routeDB: https://rutedb.entur.org/
    stopPlace: https://stoppested.entur.org/
    operator:

ingress:
  loadBalancerIP: 35.187.15.14