env: production
replicas: 2

gcp:
  databaseInstance: entur-ror-prod:europe-west1:baba-db-1=tcp:5432

keycloak:
  url:  https://auth.entur.org/auth
auth0:
  ror:
    url: https://auth2.entur.org/
    audience: https://ror.api.entur.io
  admin:
    client:
      id: GLBqcAUgBKVLby3ur9KTqvqraTUmnXvD
    domain: ror-entur.eu.auth0.com

mail:
  newUserFrom: noreply@entur.org
  link:
    routeDB: https://rutedb.entur.org/
    stopPlace: https://stoppested.entur.org/
    operator:

ingress:
  loadBalancerIP: 35.205.233.237

monitoringEnabled: false