env: staging
replicas: 2

gcp:
  databaseInstance: entur-ror-test:europe-west1:baba-db-1=tcp:5432
  exchangeKeyName: marduk-exchange-radon-storage-key

keycloakUrl: https://kc-stage.devstage.entur.io/auth

mail:
  newUserFrom: noreply-staging@entur.org
  link:
    routeDB: https://rutedb.staging.entur.org/
    stopPlace: https://stoppested.staging.entur.org/
    operator: https://operator-stage.rutebanken.org/

ingress:
  loadBalancerIP: 130.211.80.129
