env: staging
replicas: 2

gcp:
  databaseInstance: entur-ror-test:europe-west1:baba-db-1=tcp:5432

keycloak:
  url:  https://kc-stage.devstage.entur.io/auth
auth0:
  ror:
    url: https://ror-entur-staging.eu.auth0.com/
    audience: https://ror.api.staging.entur.io
  admin:
    client:
      id:
    domain: ror-entur-staging.eu.auth0.com

mail:
  newUserFrom: noreply-staging@entur.org
  link:
    routeDB: https://rutedb.staging.entur.org/
    stopPlace: https://stoppested.staging.entur.org/
    operator: https://operator-stage.rutebanken.org/

ingress:
  loadBalancerIP: 130.211.80.129

monitoringEnabled: true
