keycloakUrl: https://kc-stage.devstage.entur.io/auth
mail:
  newUserFrom: noreply-staging@entur.org
  link:
    routeDB: https://rutedb.staging.entur.org/
    stopPlace: https://stoppested.staging.entur.org/
    operator: https://operator-stage.rutebanken.org/