apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-organisations
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.organizations.name }}{{ .Values.ingress.domain }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "baba.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
