apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "baba.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "baba.name" . }}
  sessionAffinity: None
  type: ClusterIP
